interests = dict()

interests["interest-art"] = "Art"
interests["interest-music"] = "Music"
interests["interest-programming"] = "Programming"
interests["interest-helping-others"] = "Helping others"
interests["interest-people"] = "People"
interests["interest-team"] = "Working in a team"
interests["interest-alone"] = "Working alone"
interests["interest-justice"] = "Justice"
interests["interest-solving-problems"] = "Solving problems"
interests["interest-animals"] = "Working with animals"
interests["interest-creation"] = "Creating something"
interests["interest-cars"] = "Cars"
interests["interest-how-things-work"] = "Understanding how things work"